/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventariosRouteImport } from './routes/inventarios'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminOperadoresRouteImport } from './routes/admin.operadores'
import { Route as InventarioIdResumoRouteImport } from './routes/inventario.$id.resumo'
import { Route as InventarioIdContagemRouteImport } from './routes/inventario.$id.contagem'
import { Route as InventarioIdAnaliseRouteImport } from './routes/inventario.$id.analise'

const InventariosRoute = InventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperadoresRoute = AdminOperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => AdminRoute,
} as any)
const InventarioIdResumoRoute = InventarioIdResumoRouteImport.update({
  id: '/inventario/$id/resumo',
  path: '/inventario/$id/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIdContagemRoute = InventarioIdContagemRouteImport.update({
  id: '/inventario/$id/contagem',
  path: '/inventario/$id/contagem',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIdAnaliseRoute = InventarioIdAnaliseRouteImport.update({
  id: '/inventario/$id/analise',
  path: '/inventario/$id/analise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inventarios': typeof InventariosRoute
  '/admin/operadores': typeof AdminOperadoresRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/': typeof AdminIndexRoute
  '/inventario/$id/analise': typeof InventarioIdAnaliseRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
  '/inventario/$id/resumo': typeof InventarioIdResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/admin/operadores': typeof AdminOperadoresRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin': typeof AdminIndexRoute
  '/inventario/$id/analise': typeof InventarioIdAnaliseRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
  '/inventario/$id/resumo': typeof InventarioIdResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inventarios': typeof InventariosRoute
  '/admin/operadores': typeof AdminOperadoresRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/': typeof AdminIndexRoute
  '/inventario/$id/analise': typeof InventarioIdAnaliseRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
  '/inventario/$id/resumo': typeof InventarioIdResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inventarios'
    | '/admin/operadores'
    | '/admin/produtos'
    | '/admin/'
    | '/inventario/$id/analise'
    | '/inventario/$id/contagem'
    | '/inventario/$id/resumo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventarios'
    | '/admin/operadores'
    | '/admin/produtos'
    | '/admin'
    | '/inventario/$id/analise'
    | '/inventario/$id/contagem'
    | '/inventario/$id/resumo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/inventarios'
    | '/admin/operadores'
    | '/admin/produtos'
    | '/admin/'
    | '/inventario/$id/analise'
    | '/inventario/$id/contagem'
    | '/inventario/$id/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InventariosRoute: typeof InventariosRoute
  InventarioIdAnaliseRoute: typeof InventarioIdAnaliseRoute
  InventarioIdContagemRoute: typeof InventarioIdContagemRoute
  InventarioIdResumoRoute: typeof InventarioIdResumoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventarios': {
      id: '/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof InventariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operadores': {
      id: '/admin/operadores'
      path: '/operadores'
      fullPath: '/admin/operadores'
      preLoaderRoute: typeof AdminOperadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/inventario/$id/resumo': {
      id: '/inventario/$id/resumo'
      path: '/inventario/$id/resumo'
      fullPath: '/inventario/$id/resumo'
      preLoaderRoute: typeof InventarioIdResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/$id/contagem': {
      id: '/inventario/$id/contagem'
      path: '/inventario/$id/contagem'
      fullPath: '/inventario/$id/contagem'
      preLoaderRoute: typeof InventarioIdContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/$id/analise': {
      id: '/inventario/$id/analise'
      path: '/inventario/$id/analise'
      fullPath: '/inventario/$id/analise'
      preLoaderRoute: typeof InventarioIdAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOperadoresRoute: typeof AdminOperadoresRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOperadoresRoute: AdminOperadoresRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InventariosRoute: InventariosRoute,
  InventarioIdAnaliseRoute: InventarioIdAnaliseRoute,
  InventarioIdContagemRoute: InventarioIdContagemRoute,
  InventarioIdResumoRoute: InventarioIdResumoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
