/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventariosRouteImport } from './routes/inventarios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioIdContagemRouteImport } from './routes/inventario.$id.contagem'

const InventariosRoute = InventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIdContagemRoute = InventarioIdContagemRouteImport.update({
  id: '/inventario/$id/contagem',
  path: '/inventario/$id/contagem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/inventario/$id/contagem': typeof InventarioIdContagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventarios' | '/inventario/$id/contagem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventarios' | '/inventario/$id/contagem'
  id: '__root__' | '/' | '/inventarios' | '/inventario/$id/contagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventariosRoute: typeof InventariosRoute
  InventarioIdContagemRoute: typeof InventarioIdContagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventarios': {
      id: '/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof InventariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/$id/contagem': {
      id: '/inventario/$id/contagem'
      path: '/inventario/$id/contagem'
      fullPath: '/inventario/$id/contagem'
      preLoaderRoute: typeof InventarioIdContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventariosRoute: InventariosRoute,
  InventarioIdContagemRoute: InventarioIdContagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
