// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqtfpmvnusdcwcbmgqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcXRmcG12bnVzZGN3Y2JtZ3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5NDE1NjMsImV4cCI6MjA5NDUxNzU2M30.45-Y-9dhHnxOilQWQ7EGEI1Is9gRfOx-Sn78xuAq90s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});